### ISSUE TITLE
Title Focus Issue While Creating New Posts

### ISSUE THREAD

**Issue by ahmadawais** [xwp/wp-customize-posts#209]
This is UX flow issue. When I click the <kbd>+</kbd> button to create a new post, the first thing I want to do is add a title. Here's where I face a UX glitch.

Current UX-Flow
- Click the <kbd>+</kbd> button
- Either press <kbd>tab</kbd> to select the title or click on the title (which BTW doesn't pre-select the existing value i.e. `(no title)`) and add a new title.

Better UX-Flow would be:
- Click the <kbd>+</kbd> button
- The title element is pre-focused, i.e. `(no title)` value is pre-selected and all I have to do is type the title.

![](https://i.imgur.com/lz3IJuu.png)
![](https://i.imgur.com/RycyMEb.png)

**Comment by ahmadawais** [comment]
There should be a way for adding `tabindex="1"` to WP_Customize_Dynamic_Control type for each control. That would bring the focus right where it belongs.

**Comment by westonruter** [comment]
@ahmadawais this should be fixed in #206. Could you test it?

**Comment by ahmadawais** [comment]
@westonruter Just tested it, UX Flow is still broken. 

- [x] Clicking on the input selects all, which is good!
- [ ] Auto-focus on the title (Currently, I have to press <kbd>TAB</kbd> or click with the pad. It should be autofocused)

**Comment by westonruter** [comment]
@ahmadawais sure enough, it isn't working for me now either. I just amended the PR with another commit which may fix the issue: https://github.com/xwp/wp-customize-posts/pull/206/commits/cf224e2e4db7710874b31f87d6e2155f74c28d2d

Could you re-try? It's not pretty how we currently have to include these delay/defer calls.

**Comment by ahmadawais** [comment]
@westonruter Yep! Now it is working but the `500` delay is too much. I set it to `100` and it works fine. 

Talking about the `customize-posts-panel.js` file Line # 198
```							}, 100 );
```
